# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13fee037ce548070b85be46d837bac91c99208504830a72f2d131d1ec3357b0ca4be447d79263d255a15cf719924bed05bc453aeb41a657e009612a865bb116c

test:
  secret_key_base: 4812657a8f77d37646e1f2ea6c546007ca7c7251170adb9236d497bd3e21c57e490e3c873f6186fcbf61fe0b65ab959eeb45e6cb536d8b8f5ab3ca497cf9c1e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
